### PR TITLE
feat: add support for 1.21.1

### PR DESCRIPTION
**Pull request by AndyReckt**
This commit and PR changes the data version int to 3955, which is the required one for 1.21.1, and thus allows support for 1.21.1

### CODE REVIEW

**Comment by GrayR0ot** [comment]
Maybe you can let the 1.20 with 3953 & add a new line of 1.20.1 for 3955 ?

**Review by GrayR0ot — CHANGES_REQUESTED** [review]
Maybe you can let the 1.20 with 3953 & add a new line of 1.20.1 for 3955 ?

**Comment by AndyReckt** [comment]
@GrayR0ot 
> Maybe you can let the 1.20 with 3953 & add a new line of 1.20.1 for 3955 ?

it should still work with 1.21 even with this change, as the code checks if the `dataVersion` is smaller or equal to `requiredDataVersion`
```java
for (NMSVersionRequirement versionData : versions) {
     if (dataVersion <= versionData.requiredDataVersion) {
           nmsPackageVersion = versionData.versionName;
           break;
      }
}
```

**Review by GrayR0ot — APPROVED** [review]

**Comment by OmerBenGera** [comment]
I didn't see your MR and implemented it myself
Anyways thanks for your help bud, really appreciated <3

**Pull request closed without merging**
